      SUBROUTINE CPUSEC(TUSER,TTOTAL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C         ROUTINE FOR TIMING (USER AND USER+SYSTEM TIME IN SECONDS).
C         Uses standard Fortran CPU_TIME intrinsic.
C
      CALL CPU_TIME(TUSER)
      TTOTAL = TUSER
      RETURN
      END
