      SUBROUTINE MICROCI(ECONE,EQNM)
C
C
      use venus_params
      use venus_data, only: B_H => B
      use venus_data
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C
C  PROGRAM TO SAMPLE A MICROCANONICAL ENSEMBLE AT A
C  CONICAL INTERSECTION.
C
C      RANDOMLY CHOSE E2, THE ENERGY FOR THE CONE’S TWO
C      DEGREES OF FREEDOM.  THE PROBABILITY OF E2 IS
C      PROPORTIONAL TO THE CONE’S DENSITY OF STATES FOR E2 X THE
C      DENSITY OF STATES FOR THE 3N-8 REMAINING DEGREES OF
C      FREEDOM WITH ENERGY E - E2.
C
C         THE CLASSICAL DENSITY OF STATES FOR THE CONE IS:
C             CONSTANT X SQRT(MX X MY) E2**2/(SX + G)/(SY + H)
C
C             DETERMINE THE MOST PROBABLE VALUE FOR E2, TO
C             WITHIN E/5000, AND ITS RELATED DENSITY
C
      N3NM8=3*NATOMA(1)-8
C
C
C
      EN=ENMTA*C1
      NSTEPS=1000
C
C     CALCULATING ZPE FOR 3N-8 OSCILLATORS
C
      ZPEQNM=0D0
      DO I=1,N3NM8
         ZPEQNM=ZPEQNM+(WWA(I)*C6*C7*0.5D0)
      ENDDO
      EN=EN-ZPEQNM
C
C
       ECONE=0D0
       RHOTEST=0D0
       ECONEMAX=0D0
       RHOMAX=0D0
C
C
       PXMAX=DSQRT(2.0D0*EN)
       PXMIN=DSQRT(2.0D0*EN)*(-1D0)
       PYMAX=DSQRT(2.0D0*EN)
       PYMIN=DSQRT(2.0D0*EN)*(-1D0)
C
C      CALCULATING MAXIMUM AND MINIMUM VALUES FOR CONEXX, CONEYY, 
C      CONEPX AND CONEPY FROM 2D CONE HAMILTONIAN
C      V(X,Y) = SX*X + SY*Y + DSQRT((G*X)**2 + (H*Y)**2)
C
       IF ((SXCI .EQ. 0.0D0) .AND. (SYCI .EQ. 0.0D0)) THEN
          A=EN/GGCI
          B=EN/HHCI
          LAMBDA=0D0
       ELSE
          IF (SXCI/GGCI .GT. SYCI/HHCI) THEN
             LAMBDA=((SXCI/GGCI)**2+(SYCI/HHCI)**2)/((SXCI/GGCI)*
     *               DSQRT(((SYCI/HHCI)/(SXCI/GGCI))**2+1D0))
             A=EN/(1D0-LAMBDA**2)
             B=DSQRT(A**2*(1D0-LAMBDA**2))
          ELSE
             LAMBDA=((SYCI/HHCI)**2+(SXCI/GGCI)**2)/((SYCI/HHCI)*
     *               DSQRT(((SXCI/GGCI)/(SYCI/HHCI))**2+1D0))
             B=EN/(1D0-LAMBDA**2)
             A=DSQRT(B**2*(1D0-LAMBDA**2))
          ENDIF
       ENDIF
C
      XXMIN=-A-(LAMBDA**2)
      XXMAX=A-(LAMBDA**2)
      YYMIN=-B-(LAMBDA**2)
      YYMAX=B-(LAMBDA**2)
C
      PXLEN=PXMAX-PXMIN
      PYLEN=PYMAX-PYMIN
      XXLEN=XXMAX-XXMIN
      YYLEN=YYMAX-YYMIN
C
C
      CALL VOLPSCONE(EN,CCDSCI)
C
C
      ENWN=(EN/C1)*CAL2CM
      DELTAE=ENWN/DBLE(NSTEPS)
      CCDSCI=CCDSCI*((C1/CAL2CM)**3)
C
C
      DO I=1,NSTEPS
         RHO=RHOTEST
         ECONE=ECONE+DELTAE
C
C     CLASSICAL DENSITY OF STATES FOR G AND H COORDINATES
C
         RHOCONE=3D0*CCDSCI*(ECONE**2) 
C
C
         EQNM=ENWN-ECONE
C
C     QUANTUM DENSITY OF STATES FOR REMAINING 3N-8 COORDINATES
C
         CALL DENQ(WWA,EQNM,N3NM8,RHOQNM)
C
C
         RHOTEST=RHOCONE*RHOQNM
         IF (RHOTEST .GT. RHOMAX) THEN
            RHOMAX=RHOTEST
            ECONEMAX=ECONE
         ENDIF
C
C
         EKCAL=ECONE/CAL2CM
      ENDDO
C
C
C  CHOOSING ECONE USING NEWMAN REJECTION METHOD
C
      DO
         RAND=RAND0(ISEED)
         ECONE=ENWN*RAND
         EQNM=ENWN-ECONE
C
         RHOECONE=3*CCDSCI*(ECONE**2)
C
         CALL DENQ(WWA,EQNM,N3NM8,RHOQNM)
C
         RHOTEST=RHOCONE*RHOQNM
         DUM1=RHOTEST/RHOMAX
C
         IF (DUM1 .GT. RAND) EXIT
C
      ENDDO
C
C
C  CHANGING ENERGY UNITS FROM WN TO SIMULATION UNIT
C
      ECONE=(ECONE/CAL2CM)*C1
      EQNM=(EQNM/CAL2CM)*C1
C
C
C  SELECTING QX, QY, PX AND PY CLASSICALLY  
C
      DO
         RAND=RAND0(ISEED)
         CONEXX=XXLEN*RAND+XXMIN
         RAND=RAND0(ISEED)
         CONEYY=YYLEN*RAND+YYMIN
         RAND=RAND0(ISEED)
         CONEPX=PXLEN*RAND+PXMIN
C
C
         DUM1=((GGCI*CONEXX)**2)+((HHCI*CONEYY)**2)
         DUM2=SXCI*CONEXX+SYCI*CONEYY+DSQRT(DUM1)
         DUM3=ECONE-((CONEPX**2)/2.0D0)-DUM2
         DUM4=2D0*DUM3
C
C
         IF (DUM4 .GT. 0D0) THEN
            CONEPY=DSQRT(DUM4)
C    
C         TESTING SELECTED PY 
C         THIS PART HAS TO BE CORRECTED BY USING VELOCITY
C
            DUM1=(1D0/CONEPY)/1000D0
            RAND=RAND0(ISEED)
C
C
            IF (DUM1 .GT. RAND) THEN
               RAND=RAND0(ISEED)
               IF (RAND .LT. 0.5D0) CONEPY=-CONEPY
               EXIT
            ENDIF
         ENDIF
C
C
      ENDDO
C
C
C
      RETURN
      END SUBROUTINE MICROCI
