      SUBROUTINE ROTATEX(N)
      use venus_params
      use venus_data
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         RANDOMLY ROTATE A MOLECULE ABOUT ITS CENTER OF MASS BY
C         EULER'S ANGLES.
C
C
C         CENTER OF MASS COORDINATES(QQ) AND MOMENTA(PP) ARE PASSED FROM
C         SUBROUTINES CENMAS AND ANGVEL THROUGH COMMON BLOCK WASTE.
C
      RAND=RAND0(ISEED)
      PHI=TWOPI*RAND
      SNPHI=SIN(PHI)
      CSPHI=COS(PHI)
      DO I=1,N
      J=3*LL(I)
         Q(J-1)=QQ(J-1)*CSPHI-QQ(J)*SNPHI
         Q(J)=QQ(J-1)*SNPHI+QQ(J)*CSPHI
         QQ(J-1)=Q(J-1)
         QQ(J)=Q(J)
         P(J-1)=PP(J-1)*CSPHI-PP(J)*SNPHI
         P(J)=PP(J-1)*SNPHI+PP(J)*CSPHI
         PP(J-1)=P(J-1)
         PP(J)=P(J)
      ENDDO
      RETURN
      END

      SUBROUTINE ROTATEX_b(PHI,N) !2024.11.14
      use venus_data, only: PHI_H => PHI
      use venus_data
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         RANDOMLY ROTATE A MOLECULE ABOUT ITS CENTER OF MASS BY
C         EULER'S ANGLES.
C
C
C         CENTER OF MASS COORDINATES(QQ) AND MOMENTA(PP) ARE PASSED FROM
C         SUBROUTINES CENMAS AND ANGVEL THROUGH COMMON BLOCK WASTE.
C
      SNPHI=SIN(PHI)
      CSPHI=COS(PHI)
      DO I=1,N
      J=3*LL(I)
         Q(J-1)=QQ(J-1)*CSPHI-QQ(J)*SNPHI
         Q(J)=QQ(J-1)*SNPHI+QQ(J)*CSPHI
         QQ(J-1)=Q(J-1)
         QQ(J)=Q(J)
         P(J-1)=PP(J-1)*CSPHI-PP(J)*SNPHI
         P(J)=PP(J-1)*SNPHI+PP(J)*CSPHI
         PP(J-1)=P(J-1)
         PP(J)=P(J)
      ENDDO
      RETURN
      END
