subroutine ROTATE(N)
  use venus_params
  use venus_data
  implicit none
  integer,  intent(in)    :: N
  real(8)  :: RAND, RPHI, CSTHTA, RCHI, RTHTA, SNTHTA, SNPHI
  real(8)  :: CSPHI, SNCHI, CSCHI
  real(8)  :: RXX, RXY, RXZ, RYX, RYY, RYZ, RZX, RZY, RZZ
  integer  :: I, J, ISEED
  real(8), external :: RAND0
!
!         RANDOMLY ROTATE A MOLECULE ABOUT ITS CENTER OF MASS BY
!         EULER'S ANGLES.
!
!
!         CENTER OF MASS COORDINATES(QQ) AND MOMENTA(PP) ARE PASSED FROM
!         SUBROUTINES CENMAS AND ANGVEL THROUGH COMMON BLOCK WASTE.
!
  RAND = RAND0(ISEED)
  RPHI = TWOPI*RAND
  RAND = RAND0(ISEED)
  CSTHTA = 2.0D0*RAND-1.0D0
  RAND = RAND0(ISEED)
  RCHI = TWOPI*RAND
  RTHTA = acos(CSTHTA)
  SNTHTA = sin(RTHTA)
  SNPHI = sin(RPHI)
  CSPHI = cos(RPHI)
  SNCHI = sin(RCHI)
  CSCHI = cos(RCHI)
  RXX = CSTHTA*CSPHI*CSCHI-SNPHI*SNCHI
  RXY = -CSTHTA*CSPHI*SNCHI-SNPHI*CSCHI
  RXZ = SNTHTA*CSPHI
  RYX = CSTHTA*SNPHI*CSCHI+CSPHI*SNCHI
  RYY = -CSTHTA*SNPHI*SNCHI+CSPHI*CSCHI
  RYZ = SNTHTA*SNPHI
  RZX = -SNTHTA*CSCHI
  RZY = SNTHTA*SNCHI
  RZZ = CSTHTA
  do I = 1, N
     J = 3*LL(I)
     Q(J-2) = QQ(J-2)*RXX+QQ(J-1)*RXY+QQ(J)*RXZ
     Q(J-1) = QQ(J-2)*RYX+QQ(J-1)*RYY+QQ(J)*RYZ
     Q(J) = QQ(J-2)*RZX+QQ(J-1)*RZY+QQ(J)*RZZ
     QQ(J-2) = Q(J-2)
     QQ(J-1) = Q(J-1)
     QQ(J) = Q(J)
     P(J-2) = PP(J-2)*RXX+PP(J-1)*RXY+PP(J)*RXZ
     P(J-1) = PP(J-2)*RYX+PP(J-1)*RYY+PP(J)*RYZ
     P(J) = PP(J-2)*RZX+PP(J-1)*RZY+PP(J)*RZZ
     PP(J-2) = P(J-2)
     PP(J-1) = P(J-1)
     PP(J) = P(J)
  end do
end subroutine ROTATE

!     MODIFIED BY BIN AND YAOLONG, 2020/5/31
subroutine ROTATENO(N, NTHTA)
  use venus_params
  implicit none
  integer,  intent(in)    :: N, NTHTA
  real(8)  :: RAND, RTHTA, CSTHTA, PTHETA, PTEST
  integer  :: ISEED
  real(8), external :: RAND0
!
!         RANDOMLY ROTATE THE SOLID ANGLE BETWEEN N->O VECTOR AND
!         SURFACE NORMAL (Z AXIS PARALLEL TO ELECTRIC FIELD).
!         SAMPLE THE SOLID ANGLE THETA TO SATISFY
!         ITS DISTRIBUTION FUNCTION IN START ELECTRIC FIELD IN THE
!         FOLLOWING FORM:
!         P(THETA)=(1-COSTHETA)/2  FOR POSITIVE FIELD (+Z DIRECTION)
!         O-DOWN ORIENTATION
!         P(THETA)=(1+COSTHETA)/2  FOR NEGATIVE FIELD (-Z DIRECTION)
!         N-DOWN ORIENTATION
!         THIS IS DONE BY VON NEUMANN REJECTION METHOD.
!
!         CENTER OF MASS COORDINATES(QQ) AND MOMENTA(PP) ARE PASSED FROM
!         SUBROUTINES CENMAS AND ANGVEL THROUGH COMMON BLOCK WASTE.
!
!     VON NEUMANN REJECTION SAMPLING
!     INITIALIZE A RANDOM THETA VALUE
!     THETA REPRESENTS THE SOLID ANGLE WITH RESPECT TO SURFACE NORMAL (Z AXIS)
  do
     RAND = RAND0(ISEED)
     RTHTA = 2.0D0*PI*RAND-PI
     CSTHTA = cos(RTHTA)
     if (NTHTA == -2) then
        PTHETA = 0.5D0*(1-CSTHTA)
     else if (NTHTA == -3) then
        PTHETA = 0.5D0*(1+CSTHTA)
     else
        stop 'NTHTA < -3 HAS NOT BEEN DEFINED'
     end if
     PTEST = RAND0(ISEED)
     if (PTHETA >= PTEST) exit
  end do
!     END REJECTION SAMPLING

!     THE NO MOLECULE ORIGINALLY LIES ON X AXIS.
!     ROTATE THE MOLECULE ABOUT Y AXIS BY 90 DEGREE, AFTER WHICH NO LIES ON THE Z AXIS
  call ROTATEY(0d0, 2)

!     NOW THE MOLECULE IS ALONG Z AXIS
!     ROTATE THE MOLECULE ABOUT Y AXIS SO THAT THE SOLID ANGLE IS THETA
  call ROTATEY(CSTHTA, 2)

!     A RANDOM ROTATION ABOUT THE SURFACE NORMAL MAKES THE FINAL
!     DISTRIBUTION CYLINDRICALLY SYMEMTRIC WITH RESPECT TO THE SURFACE NORMAL
  call ROTATEZ(2)
end subroutine ROTATENO
