      SUBROUTINE ROTATEJM(NTHTA,JA,N)
      use venus_params
      use venus_data, only: NTHTA_H => NTHTA, JA_H => JA
      use venus_data
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         ROTATE A DIATOM (N=2) TO MODEL A SPECIFIC (J,M) STATE BY A VECTOR MODEL
C
      DIMENSION P1(3),P2(3),X1(3),X2(3)
C
C         CENTER OF MASS COORDINATES(QQ) AND MOMENTA(PP) ARE PASSED FROM
C         SUBROUTINES CENMAS AND ANGVEL THROUGH COMMON BLOCK WASTE.
C

C
C         THE ANGULAR MOMENTURM (J) IS INITIALLY ALONG Z AXIS
C         ROTATE THE DIATOM ABOUT Y AXIS SO THAT THE ANGLULAR MOMENTUM (J) HAS AN
C         ANGLE OF ACOS(M/SQRT(J(J+1)) WITH THE SURFACE NORMAL.
C
      CSTHTA=DBLE(NTHTA)/DSQRT(DBLE(JA**2+JA))
      SNTHTA=DSQRT(1D0-CSTHTA**2)
      CALL ROTATEY(CSTHTA,2)
C
C         THE MOLECULAR ORIENTATION IS THEN CHOSEN RANDOMLY ON A PLANE
C         PERPENDICULAR TO J
C         THIS IS ACHIEVED BY A RANDOM ROTATION ABOUT THE CURRECT J VECTOR, WHICH
C         IS DEFINED BY P1->P2
C
      P1(1)=0d0
      P1(2)=0d0
      P1(3)=0d0
      P2(1)=SNTHTA
      P2(2)=0d0
      P2(3)=CSTHTA
      RAND=RAND0(ISEED)
      PHI=TWOPI*RAND/C4
      DO I=1,2
         J=3*LL(I)+1
         DO K=1,3
            X1(3-K+1)=QQ(J-K)
         ENDDO
         CALL ROTALINE(P1,P2,X1,X2,PHI) 
         DO K=1,3
            Q(J-K)=X2(3-K+1)
            QQ(J-K)=Q(J-K)
         ENDDO
         DO K=1,3
            X1(3-K+1)=PP(J-K)
         ENDDO
         CALL ROTALINE(P1,P2,X1,X2,PHI) 
         DO K=1,3
            P(J-K)=X2(3-K+1)
            PP(J-K)=P(J-K)
         ENDDO
      ENDDO

C
C         A RANDOM ROTATION ABOUT THE SURFACE NORMAL MAKES THE FINAL
C         DISTRIBUTION CYLINDRICALLY SYMEMTRIC WITH RESPECT TO THE SURFACE NORMAL
C
      CALL ROTATEZ(2)

      RETURN
      END
