      SUBROUTINE ROTATEJKM(NTHTA,JROT,AM,N)
      use venus_params
      use venus_data, only: NTHTA_H => NTHTA, AI_H => AI
      use venus_data
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C         ROTATE A VECTOR TO ALIGN WITH Z AXIS
C         THEN ROTATE THE MOLECULE ACCORDINGLY
C
      DIMENSION Q1(3),Q2(3)
      DIMENSION WW(NDA3),A(NDA3),C(NDA3YF,NDA3YF),QCM(3),VCM(3),AM(4),
     *AI(3),COOR(NDA3),DCOOR(NDA3),PHASE(5),IPHASE(5)
      DIMENSION P1(3),P2(3),X1(3),X2(3)
C
C         CENTER OF MASS COORDINATES(QQ) AND MOMENTA(PP) ARE PASSED FROM
C         SUBROUTINES CENMAS AND ANGVEL THROUGH COMMON BLOCK WASTE.
C
C
C         ROTATE THE ANGULAR MOMENTUM (J) ABOUT THE Z AXIS TO THE XZ PLANE
C
      XT2=AM(1)
      YT2=AM(2)
      ZT2=AM(3)
      RXX=XT2/DSQRT(XT2**2+YT2**2)
      RXY=YT2/DSQRT(XT2**2+YT2**2)
      RYX=-RXY
      RYY=RXX
      DO I=1,N
      J=3*LL(I)
         Q(J-2)=QQ(J-2)*RXX+QQ(J-1)*RXY
         Q(J-1)=QQ(J-2)*RYX+QQ(J-1)*RYY
         QQ(J-2)=Q(J-2)
         QQ(J-1)=Q(J-1)
         P(J-2)=PP(J-2)*RXX+PP(J-1)*RXY
         P(J-1)=PP(J-2)*RYX+PP(J-1)*RYY
         PP(J-2)=P(J-2)
         PP(J-1)=P(J-1)
      ENDDO
         XT3=XT2*RXX+YT2*RXY
         YT3=XT2*RYX+YT2*RYY
         ZT3=ZT2
C
C         ROTATE THE ANGULAR MOMENTUM (J) IN THE XZ PLANE TO THE Z AXIS
C
      RXX=ZT2/DSQRT(XT2**2+YT2**2+ZT2**2)
      RXZ=-DSQRT(XT2**2+YT2**2)/DSQRT(XT2**2+YT2**2+ZT2**2)
      RZX=-RXZ
      RZZ=RXX
      DO I=1,N
      J=3*LL(I)
         Q(J-2)=QQ(J-2)*RXX+QQ(J)*RXZ
         Q(J)=QQ(J-2)*RZX+QQ(J)*RZZ
         QQ(J-2)=Q(J-2)
         QQ(J)=Q(J)
         P(J-2)=PP(J-2)*RXX+PP(J)*RXZ
         P(J)=PP(J-2)*RZX+PP(J)*RZZ
         PP(J-2)=P(J-2)
         PP(J)=P(J)
      ENDDO
         XT4=XT3*RXX+ZT3*RXZ
         YT4=YT3
         ZT4=XT3*RZX+ZT3*RZZ
C
C         NOW THE ANGULAR MOMENTURM (J) IS ALONG Z AXIS
C         ROTATE THE MOLECULE ABOUT Y AXIS SO THAT THE ANGLULAR MOMENTUM (J) HAS AN
C         ANGLE OF ACOS(M/SQRT(J(J+1)) WITH THE SURFACE NORMAL.
C
      CSTHTA=DBLE(NTHTA)/DSQRT(DBLE(JROT**2+JROT))
      SNTHTA=DSQRT(1D0-CSTHTA**2)
      CALL ROTATEY(CSTHTA,N)
C
C         THE MOLECULAR ORIENTATION IS THEN CHOSEN RANDOMLY ON A PLANE
C         PERPENDICULAR TO J
C         THIS IS ACHIEVED BY A RANDOM ROTATION ABOUT THE CURRECT J VECTOR, WHICH
C         IS DEFINED BY P1->P2
C
      P1(1)=0D0
      P1(2)=0D0
      P1(3)=0D0
      P2(1)=SNTHTA
      P2(2)=0D0
      P2(3)=CSTHTA
      RAND=RAND0(ISEED)
      PHI=TWOPI*RAND/C4
      DO I=1,N
         J=3*LL(I)+1
         DO K=1,3
            X1(3-K+1)=QQ(J-K)
         ENDDO
         CALL ROTALINE(P1,P2,X1,X2,PHI) 
         DO K=1,3
            Q(J-K)=X2(3-K+1)
            QQ(J-K)=Q(J-K)
         ENDDO
         DO K=1,3
            X1(3-K+1)=PP(J-K)
         ENDDO
         CALL ROTALINE(P1,P2,X1,X2,PHI) 
         DO K=1,3
            P(J-K)=X2(3-K+1)
            PP(J-K)=P(J-K)
         ENDDO
      ENDDO
C
C         A RANDOM ROTATION ABOUT THE SURFACE NORMAL MAKES THE FINAL
C         DISTRIBUTION CYLINDRICALLY SYMEMTRIC WITH RESPECT TO THE SURFACE NORMAL
C
      CALL ROTATEZ(N)
C
C!!!!!!!!NOT AVAILABLE, NEED MORE TESTS
C         IF THE POLARIZED AXIS FORMS AN ANGLE WITH THE SURFACE NORMAL,
C         WE NEED TO FINALLY ROTATE THE MOLECULE TO ALIGN WITH REPECT TO THE POLARIZED AXIS
C         THIS IS ACHIEVED BY A ROTATION OF THE THLAS ANGLE AROUND THE Y AXIS
C         THIS ROTATION CAN BE INDEED AROUND ANY AXIS
C
C         THLAS=0, LASER POLARIZATION PERPENDICULAR TO SURFACE
C         THLAS=90, LASER POLARIZATION PARALLEL TO THE SURFACE
C
C      CTHLAS=DCOS(THLAS*C4)
C      CALL ROTATEY(CTHLAS,N)

      RETURN
      END
