      SUBROUTINE VOLPSCONE(ETOT,CCDSCI)
C
      use venus_data
      use venus_params
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C     Local variables (formerly COMMON/PAR1CI/ and COMMON/PAR2CI/)
      real(8), save :: SXCI,SYCI,GGCI,HHCI
      real(8), save :: PXMAX,PXMIN,PYMAX,PYMIN,XXMAX,XXMIN,YYMAX,
     *YYMIN,PXLEN,PYLEN,XXLEN,YYLEN,CONEXX,CONEYY,CONEPX,CONEPY,N3NM8
      INTEGER PCOUNT
C
C
      VOLUME_BOX=PXLEN*PYLEN*XXLEN*YYLEN
C
C
      PCOUNT=0
C
C     PICK A POINT IN THE BOX AT RANDOM
C
      DO I=1,1000000
         RAND=RAND0(ISEED)
         CONEPX=RAND*PXLEN+PXMIN
         RAND=RAND0(ISEED)
         CONEXX=RAND*XXLEN+XXMIN
         RAND=RAND0(ISEED)
         CONEPY=RAND*PYLEN+PYMIN
         RAND=RAND0(ISEED)
         CONEYY=RAND*YYLEN+YYMIN
C
C        ACCEPT THAT POINT IF ECAL < ETOT
C
         DUM1=(CONEPX**2)/2.0D0+(CONEPY**2)/
     *               2.0D0+SXCI*CONEXX+SYCI*CONEYY
         DUM2=DSQRT((GGCI*CONEXX)**2 + (HHCI*CONEYY)**2)
         ECAL=DUM1+DUM2
         IF (ECAL .LT. ETOT) THEN
           PCOUNT=PCOUNT+1
         ENDIF
      ENDDO
C
C     DETERMINE VOLUME OF PHASE-SPACE BY RATIO OF ACCEPTED POINTS
C     TIMES TOTAL VOLUME OF BOX
C
      VOLUME_PS=(DBLE(PCOUNT)/DBLE(1000000))*VOLUME_BOX
C
C     CCDSCI : CONSTANT FOR CALCULATING CLASSICAL SUM OF STATES
C              AND DENSITY OF STATES FOR THE 2D CONE HAMILTONIAN
C
      CCDSCI=VOLUME_PS/((ETOT**3)*((C7*2.0D0*PI)**2))
C
C
      RETURN
      END SUBROUTINE VOLPSCONE
