#!/usr/bin/env bash
# prebuild.sh <srcdir> <builddir> - the two build-generated artifacts (K3, E11 drag-in):
#   <builddir>/registry_gen.f90 : the aggregate registration module - every reg_*.f90
#       under methods/ and systems/ enters here. NAMING CONTRACT: a methods/ reg
#       module's entry point is <module_name>_all (the E11 reg_<system>_all rule;
#       reg_adiabatic -> reg_adiabatic_all) and it MAY also host <module_name>_init
#       (the member-parameter load - buffered input keys -> the member's own init).
#       A systems/ (container) reg module's entry point is <module_name>_slots - the
#       single handover that fills the schedule slots of interface/container_sched,
#       which then owns the run order and the initialization-assembly guard.
#       A fresh make picks a dragged-in folder up automatically.
#   <builddir>/depend.mk        : object-level use-dependencies for make - depending on
#       the DEFINING unit's .o (not the .mod) sidesteps make's two-product problem and
#       is parallel-safe (the .mod is written before the .o completes).
# Idempotent: reruns rewrite identical content.
set -euo pipefail
SRC="$1"; BLD="$2"
mkdir -p "$BLD"

# sync-protect: emit through <name>.tmp; overwrite the target ONLY when content differs
# (stable timestamps when unchanged - the Makefile runs this every make, phony)
sync_out() { # $1 target, $2 tmp
   if [ ! -f "$1" ] || ! cmp -s "$1" "$2"; then mv -f "$2" "$1"; else rm -f "$2"; fi
}

# ---------- gather sources ----------
tree_files=$(cd "$SRC" && ls -1 *.f90 */*.f90 2>/dev/null || true)
sys_files=$(cd "$SRC/.." && ls -1 systems/*/*.f90 2>/dev/null || true)

# ---------- module -> defining source map ----------
declare -A mod_owner
scan_modules() { # $1 = source path (relative for printing), reads file content from $2
   local rel="$1" f="$2" m
   for m in $(grep -E '^module[[:space:]]+[a-zA-Z_]' "$f" | tr -d '' | awk '{print $2}' || true); do
      mod_owner["$m"]="$rel"
   done
}
while IFS= read -r f; do
   [ -z "$f" ] && continue
   scan_modules "$f" "$SRC/$f"
done <<< "$tree_files"
while IFS= read -r f; do
   [ -z "$f" ] && continue
   scan_modules "../$f" "$SRC/../$f"
done <<< "$sys_files"

# ---------- registry_gen.f90 ----------
# methods/ reg modules: the <module_name>_all registrants (methods only - a container
#   registers nothing itself; its slots go through the schedule)
mods=""
for f in $tree_files; do
   case "$f" in methods/reg_*.f90) mods="$mods $(basename "${f%.f90}")";; esac
done

# a methods/ reg module MAY also host <module_name>_init - the member-parameter load
#   entry (buffered input keys -> the member's own init; the reg file that owns the
#   member's registration owns its initialization assembly). Probe each reg source for
#   the routine; the probe only builds the aggregate, never gates the drag-in.
probe_init() { # $1 = module name, $2 = source content path; prints the name when hosted
   if grep -Eq "^[[:space:]]*subroutine[[:space:]]+${1}_init\(" "$2"; then
      printf '%s\n' "$1"
   fi
   return 0
}
imods=""
for f in $tree_files; do
   case "$f" in methods/reg_*.f90) imods="$imods $(probe_init "$(basename "${f%.f90}")" "$SRC/$f")";; esac
done
has_init() { case " $imods " in *" $1 "*) return 0;; *) return 1;; esac }

# systems/ (container) reg modules: each hosts <module_name>_slots - the single
#   handover filling the schedule slots (interface/container_sched). The handover is
#   probed per source; the schedule then runs the slots at their lifecycle points.
probe_slots() { # $1 = module name, $2 = source content path; prints the name when hosted
   if grep -Eq "^[[:space:]]*subroutine[[:space:]]+${1}_slots\(" "$2"; then
      printf '%s\n' "$1"
   fi
   return 0
}
zmods=""
for f in $sys_files; do
   case "$f" in */reg_*.f90) zmods="$zmods $(probe_slots "$(basename "${f%.f90}")" "$SRC/../$f")";; esac
done
{
   echo "! registry_gen.f90 - BUILD-GENERATED by scripts/prebuild.sh (do not edit)"
   echo "! The aggregate registration module (E11/E14/E17-E19): every reg_*.f90 under"
   echo "! methods/ (method packages) and systems/ (the containers) enters here -"
   echo "! dragging a new folder in is the whole installation act."
   echo "! registry_gen_keys() runs BEFORE the parse: each container hands its slots"
   echo "! over (reg_<system>_slots fills the schedule slots), then the schedule runs"
   echo "! the key-vocabulary slot so the grammar admits the container key names."
   echo "! registry_gen_all() is the registration entry the driver calls at assembly:"
   echo "! every methods/ _all first, then the schedule's registration-time slots"
   echo "! (force slot, method rows, registration-time exports)."
   echo "! registry_gen_init() is the initialization-assembly aggregate: every methods/"
   echo "! _init entry (unselected members skip inside their own guard), then the"
   echo "! schedule's seam slots (the guard lives once in container_sched_init)."
   echo "module registry_gen"
   echo "   use container_sched, only: container_sched_keys, container_sched_all, &"
   echo "                              container_sched_init"
   for m in $mods; do
      names="${m}_all"
      if has_init "$m"; then names="$names, ${m}_init"; fi
      echo "   use $m, only: $names"
   done
   for z in $zmods; do
      echo "   use $z, only: ${z}_slots"
   done
   echo "   implicit none"
   echo "   private"
   echo "   public :: registry_gen_all"
   echo "   public :: registry_gen_init"
   echo "   public :: registry_gen_keys"
   echo "contains"
   echo "   subroutine registry_gen_keys()"
   for z in $zmods; do echo "      call ${z}_slots()"; done
   echo "      call container_sched_keys()"
   echo "   end subroutine registry_gen_keys"
   echo "   subroutine registry_gen_all()"
   for m in $mods; do echo "      call ${m}_all()"; done
   echo "      call container_sched_all()"
   echo "   end subroutine registry_gen_all"
   echo "   subroutine registry_gen_init()"
   for m in $imods; do echo "      call ${m}_init()"; done
   echo "      call container_sched_init()"
   echo "   end subroutine registry_gen_init"
   echo "end module registry_gen"
} > "$BLD/registry_gen.f90.tmp"
sync_out "$BLD/registry_gen.f90" "$BLD/registry_gen.f90.tmp"

# the generated unit defines a module too - it must enter the module->owner map BEFORE
# dependency emission (a driver `use registry_gen` resolves through this entry)
scan_modules registry_gen "$BLD/registry_gen.f90"

# ---------- depend.mk ----------
objpath() { # tree: globals/state.f90 -> build/globals/state.o ; sys: systems/x/y.f90 -> build/sys/x/y.o ; generated: registry_gen
   case "$1" in
      registry_gen)      echo "$BLD/registry_gen.o" ;;
      ../*)              echo "$BLD/sys/$(echo "${1#../systems/}" | sed 's|\.f90$|.o|')" ;;
      *)                 echo "$BLD/$(echo "$1" | sed 's|\.f90$|.o|')" ;;
   esac
}
{
   echo "# depend.mk - BUILD-GENERATED by scripts/prebuild.sh (do not edit)"
   emit_deps() { # $1 = dep-owner source rel path, $2 = file content path
      local uses u d deps=""
      # || true: a use-free unit must not kill the scan
      uses=$(grep -E '^[[:space:]]*use[[:space:]]+[a-zA-Z_]' "$2" | tr -d '' | awk '{print $2}' | sed 's/,.*//' | sort -u || true)
      for u in $uses; do
         d="${mod_owner[$u]:-}"
         [ -n "$d" ] && deps="$deps $(objpath "$d")"
      done
      echo "$(objpath "$1"):$deps"
   }
   while IFS= read -r f; do
      [ -z "$f" ] && continue
      emit_deps "$f" "$SRC/$f"
   done <<< "$tree_files"
   while IFS= read -r f; do
      [ -z "$f" ] && continue
      emit_deps "../$f" "$SRC/../$f"
   done <<< "$sys_files"
   emit_deps registry_gen "$BLD/registry_gen.f90"
} > "$BLD/depend.mk.tmp"
sync_out "$BLD/depend.mk" "$BLD/depend.mk.tmp"
